### ISSUE TITLE
Add toggle to disable addon in specific tabs/pages

### ISSUE THREAD

**Issue by jpdias** [mindedsecurity/behave#1]
Hello. First and foremost, I really like this extension, so good job.

As I tried to use this extension in my everyday browser, I identified the need to be able to disable it in certain pages, since it becomes impossible to use in development environments (localhost).  

Thanks!

**Comment by wisec** [comment]
Hey!
Thanks :) okay will surely do. 
I'm planning to add a domain/page whitelist functionality, but in the meantime I'll just add a enable/disable button.

Cheers!

**Comment by wisec** [comment]
@jpdias 
let me know if it's okay 
Feel free to reopen if there's any issue. :)

**Comment by jpdias** [comment]
That's it! Thank you.
