### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by carlostkd** [mindedsecurity/behave#13]
hi
on firefox regarded i have notifications enabled i dont get any notification tested with the websites you recomend but nothing pop ups.

**Comment by wisec** [comment]
Hey, @carlostkd 

it's hard to reproduce without some details.
OS? Browser?

**Comment by geeknik** [comment]
I have notifications enabled, but they don't appear with Firefox Nightly on Fedora 31. Yes, Nightly is pre-release software but every 8 weeks Nightly graduates to Release. (:

**Comment by wisec** [comment]
@geeknik
which Window Manager?

**Comment by geeknik** [comment]
Xfce4. Other browser notifications are working as intended.

**Comment by geeknik** [comment]
Notifications started working this morning. Thank you.

**Comment by wisec** [comment]
Closing it as it seems to be working now.
