### ISSUE TITLE
XPI for Basilisk

### ISSUE THREAD

**Issue by andika207** [mindedsecurity/behave#17]
Please make a XPI file for this addon because I cannot install it on Basilisk browser
I have tried to copy paste the XPI file from Firefox extensions folder but it seems not to be supported.
maybe I am wrong and I should first contact the person behind Basilisk  @mattatobin

**Comment by mattatobin** [comment]
You are wrong.

**Comment by wisec** [comment]
@mattatobin Thanks for the reply! 

@andika207 I'm sorry, Behave! is implemented with chrome-style extension API, so according to @mattatobin, it's not supported.  

Closing the issue since it would require a complete rewrite, feel free to reopen if someone find a reliable solution :) 

Thanks for your interest @andika207 !

**Comment by mattatobin** [comment]
For the record, it wasn't so long ago that people found doing both styles of extension was a reliable solution.

**Comment by andika207** [comment]
@wisec @mattatobin  this addon runs fine on Firefox 52 although web-extensions protocol was not introduced till Firefox 57
when I installed 'behave' for the 1st time I got a error message ''Error:Please set webextensions.storage.sync.enabled to true''
 I have also installed 'behave' on the '360 secure browser' but it doesn't detect any anomaly when surfing on ebay (very strange)

**Comment by mattatobin** [comment]
Basilisk isn't Firefox and never will be again.

**Comment by andika207** [comment]
@mattatobin from what I have read on the web site it's a hard-fork of Firefox 52

**Comment by mattatobin** [comment]
@andika207 Can we not have this discussion about your complete ignorance of the project's technical details while on someone else's issue tracker?

**Comment by andika207** [comment]
@mattatobin *_''Basilisk in turn, is a hard-fork of Firefox 52 with multiple security and privacy improvements''_* 

https://wiki.hyperbola.info/doku.php?id=en:project:iceweasel-uxp

**Comment by mattatobin** [comment]
FTR, we had to ban this user at our org for repeated issue tracker spam because they would not accept "no" as an answer. Be wary.

**Comment by andika207** [comment]
@mattatobin -first, you didn't reply to the post above in which you got ridiculed by stating that Basilisk is not based on Firefox 52

-second, it's not that I don't accept a NO as an answer but time has proven you are a liar because Basilisk doesn't have the multi process mode enabled because you don't want not because this feature is not available in any UXP application

-third, you are just fat dictator hidden behind a computer that deletes my posts for no apparent reason, maybe because I wrote SERPENT and that makes you feel bad... and Yes the Serpent @roytam1 with multi process performs a lot better than the Basilisk browser. https://github.com/MoonchildProductions/Basilisk/issues/25#issuecomment-663821909

-fourth, we know you hate XP but please stop trolling and posting shit on other groups @Feodor2 in order to attack me. https://github.com/Feodor2/Centaury/issues/11#issuecomment-663972900

**Comment by wisec** [comment]
Comments deleted because they were going off topic, nothing else :)
