### ISSUE TITLE
Extension triggers on local domains

### ISSUE THREAD

**Issue by Benno1308** [mindedsecurity/behave#4]
Hey there,
apps like pgAdmin hosted locally trigger the portscanning and rebind monitoring (Tested in firefox, dont know about chrome).

Portscan log:
![Portscan log](https://i.a200k.xyz/RX4IW.png)

DNS Rebind log:
![DNS Rebind log](https://i.a200k.xyz/KkIQe.png)

I don't know if this expected behaviour, but either disabling the monitoring for localhost or allowing the user to manage a whitelist would prob. mitigate this problem.

**Comment by wisec** [comment]
Hi @Benno1308 ,
Thanks for reporting this, I think it's related to #3 which I should already have a fix I plan to release in the next couple of days.

Whitelisting is actually in the TODO list and I'll hopefully implement it soon.

**Comment by wisec** [comment]
It should be fixed.
Wait for the next release on WebStore
Thanks!

**Comment by wisec** [comment]
@Benno1308 feel free to reopen if the issue occurs again.
